# Generated by Django 5.1.4 on 2024-12-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_newsitem_anons_remove_newsitem_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
