# Generated by Django 5.1.4 on 2024-12-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_delete_newsitem_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
