# Generated by Django 5.1.4 on 2024-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time'),
        ),
    ]
