# Generated by Django 5.1.4 on 2024-12-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name_title')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
