# Generated by Django 5.1.4 on 2024-12-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_photo_alter_articles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('anons', models.TextField()),
                ('text', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
    ]
